import type { Vehicle } from "@/lib/types";
import car1 from "@/assets/car-1.jpg";
import car2 from "@/assets/car-2.jpg";
import car3 from "@/assets/car-3.jpg";
import car4 from "@/assets/car-4.jpg";

const images = [car1, car2, car3, car4];
const img = (i: number): string => images[i % images.length];

const NOW = new Date().toISOString();

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: "demo-1",
    name: "BMW 5 Series",
    make: "BMW",
    model: "5 Series",
    price: 42500,
    mileage: 28000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Automatic",
    description: "Impeccably maintained BMW 5 Series with full service history. Premium leather interior, adaptive cruise control, and panoramic sunroof.",
    features: ["Leather Interior", "Panoramic Roof", "Adaptive Cruise", "Parking Assist", "Heated Seats"],
    status: "available",
    in_carousel: true,
    view_count: 142,
    image_url: img(0),
    image_urls: [img(0), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-2",
    name: "Mercedes GLC",
    make: "Mercedes-Benz",
    model: "GLC",
    price: 55800,
    mileage: 15000,
    year: 2023,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo Diesel I4",
    transmission: "Automatic",
    description: "Near-new Mercedes GLC in stunning Cavansite Blue. AMG Line package with 20-inch alloys and Burmester sound system.",
    features: ["AMG Line", "Burmester Audio", "360° Camera", "Air Suspension", "Ambient Lighting"],
    status: "available",
    in_carousel: true,
    view_count: 178,
    image_url: img(1),
    image_urls: [img(1), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-3",
    name: "Audi S5 Sportback",
    make: "Audi",
    model: "S5 Sportback",
    price: 48900,
    mileage: 32000,
    year: 2021,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L TFSI V6",
    transmission: "Automatic",
    description: "Audi S5 Sportback with the legendary 3.0 TFSI engine. Quattro all-wheel drive, virtual cockpit, and Matrix LED headlights.",
    features: ["Quattro AWD", "Virtual Cockpit", "Matrix LED", "Bang & Olufsen", "Sport Differential"],
    status: "available",
    in_carousel: true,
    view_count: 95,
    image_url: img(2),
    image_urls: [img(2), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-4",
    name: "Porsche Cayenne",
    make: "Porsche",
    model: "Cayenne",
    price: 72000,
    mileage: 22000,
    year: 2022,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "3.0L V6 Hybrid",
    transmission: "Automatic",
    description: "Porsche Cayenne E-Hybrid in pristine white. Sport Chrono package, PASM air suspension, and 14-way adaptive sport seats.",
    features: ["Sport Chrono", "Air Suspension", "BOSE Audio", "Panoramic Roof", "Sport Exhaust"],
    status: "available",
    in_carousel: true,
    view_count: 163,
    image_url: img(3),
    image_urls: [img(3), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-5",
    name: "Toyota Camry",
    make: "Toyota",
    model: "Camry",
    price: 28500,
    mileage: 35000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.5L I4",
    transmission: "Automatic",
    description: "Reliable Toyota Camry with excellent fuel economy. Well-maintained with full dealer service history.",
    features: ["Apple CarPlay", "Lane Assist", "Blind Spot Monitor", "Dual Climate", "Keyless Entry"],
    status: "available",
    in_carousel: true,
    view_count: 87,
    image_url: img(0),
    image_urls: [img(0), img(1), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-6",
    name: "Range Rover Sport",
    make: "Land Rover",
    model: "Range Rover Sport",
    price: 68500,
    mileage: 18000,
    year: 2023,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "3.0L Turbo Diesel I6",
    transmission: "Automatic",
    description: "Range Rover Sport in Santorini Black. Dynamic pack, Meridian sound, and full off-road capability.",
    features: ["Meridian Audio", "Terrain Response", "Air Suspension", "Pixel LED", "Head-Up Display"],
    status: "available",
    in_carousel: true,
    view_count: 199,
    image_url: img(1),
    image_urls: [img(1), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-7",
    name: "Tesla Model 3",
    make: "Tesla",
    model: "Model 3",
    price: 38900,
    mileage: 20000,
    year: 2023,
    fuel: "Electric",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "Tesla Model 3 Long Range with Autopilot. Pearl White exterior with black premium interior.",
    features: ["Autopilot", "15\" Touchscreen", "Glass Roof", "Premium Audio", "Sentry Mode"],
    status: "available",
    in_carousel: false,
    view_count: 131,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-8",
    name: "Honda CR-V",
    make: "Honda",
    model: "CR-V",
    price: 32000,
    mileage: 25000,
    year: 2022,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "1.5L Turbo I4",
    transmission: "CVT",
    description: "Honda CR-V Touring with Honda Sensing suite. Spacious, reliable, and fuel-efficient.",
    features: ["Honda Sensing", "Wireless CarPlay", "Power Liftgate", "Heated Seats", "Moonroof"],
    status: "available",
    in_carousel: false,
    view_count: 54,
    image_url: img(3),
    image_urls: [img(3), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-9",
    name: "BMW M4 Competition",
    make: "BMW",
    model: "M4 Competition",
    price: 78000,
    mileage: 8000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L Twin-Turbo I6",
    transmission: "Automatic",
    description: "BMW M4 Competition in Isle of Man Green. Carbon fiber package, M Sport exhaust, and carbon ceramic brakes.",
    features: ["Carbon Ceramic Brakes", "M Sport Exhaust", "Harman Kardon", "Carbon Roof", "M Traction Control"],
    status: "available",
    in_carousel: false,
    view_count: 188,
    image_url: img(0),
    image_urls: [img(0), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-10",
    name: "Volkswagen Golf GTI",
    make: "Volkswagen",
    model: "Golf GTI",
    price: 34500,
    mileage: 12000,
    year: 2023,
    fuel: "Petrol",
    type: "Hatchback",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Manual",
    description: "VW Golf GTI Mk8 with Akrapovic exhaust. Dynamic Chassis Control and Vienna leather seats.",
    features: ["DCC Suspension", "Vienna Leather", "Digital Cockpit Pro", "Akrapovic Exhaust", "Keyless Go"],
    status: "available",
    in_carousel: false,
    view_count: 76,
    image_url: img(1),
    image_urls: [img(1), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-11",
    name: "Lexus RX 350",
    make: "Lexus",
    model: "RX 350",
    price: 52000,
    mileage: 19000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.4L Turbo I4",
    transmission: "Automatic",
    description: "Lexus RX 350 F Sport in Nori Green Pearl. Mark Levinson audio and heads-up display.",
    features: ["Mark Levinson Audio", "F Sport Package", "Panoramic View Monitor", "Adaptive Suspension", "14\" Touchscreen"],
    status: "available",
    in_carousel: false,
    view_count: 112,
    image_url: img(2),
    image_urls: [img(2), img(3), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-12",
    name: "Ford Mustang",
    make: "Ford",
    model: "Mustang",
    price: 45000,
    mileage: 15000,
    year: 2022,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "5.0L V8",
    transmission: "Manual",
    description: "Ford Mustang GT with Performance Pack Level 2. Magnetic dampers and Brembo brakes.",
    features: ["MagneRide Dampers", "Brembo Brakes", "Recaro Seats", "Active Exhaust", "Performance Pack"],
    status: "available",
    in_carousel: false,
    view_count: 155,
    image_url: img(3),
    image_urls: [img(3), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-13",
    name: "Hyundai Tucson",
    make: "Hyundai",
    model: "Tucson",
    price: 29500,
    mileage: 22000,
    year: 2023,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "1.6L Turbo Hybrid",
    transmission: "Automatic",
    description: "Hyundai Tucson Hybrid Limited with Bose audio. Parametric hidden LED daytime running lights.",
    features: ["Bose Audio", "Blind View Monitor", "Highway Driving Assist", "Rain Sensing Wipers", "Ambient Lighting"],
    status: "available",
    in_carousel: false,
    view_count: 43,
    image_url: img(0),
    image_urls: [img(0), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-14",
    name: "Audi Q7",
    make: "Audi",
    model: "Q7",
    price: 61000,
    mileage: 25000,
    year: 2022,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 7,
    engine: "3.0L TDI V6",
    transmission: "Automatic",
    description: "Audi Q7 S Line with 7 seats. Quattro AWD, virtual cockpit plus, and adaptive air suspension.",
    features: ["S Line", "7 Seats", "Virtual Cockpit Plus", "Adaptive Air Suspension", "Matrix LED"],
    status: "available",
    in_carousel: false,
    view_count: 97,
    image_url: img(1),
    image_urls: [img(1), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-15",
    name: "Mazda MX-5",
    make: "Mazda",
    model: "MX-5",
    price: 31000,
    mileage: 10000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "2.0L Skyactiv-G I4",
    transmission: "Manual",
    description: "Mazda MX-5 RF in Machine Grey. The ultimate lightweight sports car with retractable fastback.",
    features: ["Retractable Fastback", "Bose Audio", "Bilstein Dampers", "LSD", "Apple CarPlay"],
    status: "available",
    in_carousel: false,
    view_count: 68,
    image_url: img(2),
    image_urls: [img(2), img(1), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-16",
    name: "Mercedes E-Class",
    make: "Mercedes-Benz",
    model: "E-Class",
    price: 58000,
    mileage: 14000,
    year: 2023,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 + EQ Boost",
    transmission: "Automatic",
    description: "Mercedes E300 AMG Line with MBUX Superscreen. Augmented reality navigation and Burmester 4D audio.",
    features: ["MBUX Superscreen", "Burmester 4D", "AR Navigation", "Digital Light", "Air Body Control"],
    status: "available",
    in_carousel: false,
    view_count: 121,
    image_url: img(3),
    image_urls: [img(3), img(2), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-17",
    name: "Kia EV6",
    make: "Kia",
    model: "EV6",
    price: 46000,
    mileage: 8000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "Kia EV6 GT-Line with 800V ultra-fast charging. Vehicle-to-Load (V2L) capability and augmented reality HUD.",
    features: ["800V Charging", "V2L Capability", "AR Head-Up Display", "Meridian Audio", "Remote Smart Parking"],
    status: "available",
    in_carousel: false,
    view_count: 145,
    image_url: img(0),
    image_urls: [img(0), img(3), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-18",
    name: "Volvo XC60",
    make: "Volvo",
    model: "XC60",
    price: 49500,
    mileage: 20000,
    year: 2022,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo + Electric",
    transmission: "Automatic",
    description: "Volvo XC60 Recharge T8 in Crystal White. Google built-in with Bowers & Wilkins premium audio.",
    features: ["Bowers & Wilkins Audio", "Google Built-In", "Pilot Assist", "Air Purifier", "360° Camera"],
    status: "available",
    in_carousel: false,
    view_count: 33,
    image_url: img(1),
    image_urls: [img(1), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-19",
    name: "Jaguar F-Pace",
    make: "Jaguar",
    model: "F-Pace",
    price: 54000,
    mileage: 18000,
    year: 2022,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo Diesel I4",
    transmission: "Automatic",
    description: "Jaguar F-Pace R-Dynamic S in Firenze Red. Pivi Pro infotainment and configurable ambient lighting.",
    features: ["Pivi Pro", "R-Dynamic Pack", "Configurable Ambient Lighting", "Activity Key", "ClearSight Mirror"],
    status: "available",
    in_carousel: false,
    view_count: 79,
    image_url: img(2),
    image_urls: [img(2), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-20",
    name: "Subaru WRX",
    make: "Subaru",
    model: "WRX",
    price: 35000,
    mileage: 16000,
    year: 2023,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.4L Turbo Boxer H4",
    transmission: "Manual",
    description: "Subaru WRX in WR Blue Pearl. Symmetrical AWD, 11.6\" tablet-style touchscreen, and EyeSight driver assist.",
    features: ["Symmetrical AWD", "11.6\" Touchscreen", "EyeSight", "Recaro Seats", "SI-Drive"],
    status: "available",
    in_carousel: false,
    view_count: 62,
    image_url: img(3),
    image_urls: [img(3), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-21",
    name: "Chevrolet Corvette",
    make: "Chevrolet",
    model: "Corvette",
    price: 82000,
    mileage: 5000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "6.2L V8",
    transmission: "Automatic",
    description: "C8 Corvette Stingray in Torch Red. Mid-engine layout, magnetic ride control, and performance data recorder.",
    features: ["Magnetic Ride Control", "Performance Data Recorder", "Front Lift", "Bose 14-Speaker", "GT2 Seats"],
    status: "available",
    in_carousel: false,
    view_count: 193,
    image_url: img(0),
    image_urls: [img(0), img(2), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-22",
    name: "Nissan Z",
    make: "Nissan",
    model: "Z",
    price: 42000,
    mileage: 9000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "3.0L Twin-Turbo V6",
    transmission: "Manual",
    description: "New Nissan Z Performance in Seiran Blue. Twin-turbo V6 with heritage-inspired design and modern technology.",
    features: ["Launch Control", "Sport Mode", "Bose Audio", "9\" Touchscreen", "Rev Match Control"],
    status: "available",
    in_carousel: false,
    view_count: 117,
    image_url: img(1),
    image_urls: [img(1), img(3), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-23",
    name: "Genesis GV70",
    make: "Genesis",
    model: "GV70",
    price: 47000,
    mileage: 14000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.5L Turbo I4",
    transmission: "Automatic",
    description: "Genesis GV70 Sport Prestige in Havana Red. Lexicon audio, fingerprint authentication, and 3D instrument cluster.",
    features: ["Lexicon Audio", "Fingerprint Auth", "3D Cluster", "Remote Smart Parking", "E-LSD"],
    status: "available",
    in_carousel: false,
    view_count: 88,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-24",
    name: "Toyota Supra",
    make: "Toyota",
    model: "GR Supra",
    price: 52500,
    mileage: 7000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "3.0L Turbo I6",
    transmission: "Automatic",
    description: "Toyota GR Supra 3.0 Premium in Renaissance Red. BMW-sourced inline-6 with active differential.",
    features: ["Active Differential", "Adaptive Suspension", "JBL Audio", "Head-Up Display", "Wireless CarPlay"],
    status: "available",
    in_carousel: false,
    view_count: 174,
    image_url: img(3),
    image_urls: [img(3), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-25",
    name: "Rivian R1S",
    make: "Rivian",
    model: "R1S",
    price: 79000,
    mileage: 6000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 7,
    engine: "Quad Motor Electric",
    transmission: "Single-Speed",
    description: "Rivian R1S Adventure Package in Compass Yellow. Quad motor with 835 hp and air suspension.",
    features: ["Quad Motor AWD", "Air Suspension", "Camp Speaker", "Gear Tunnel", "Reinforced Underbody"],
    status: "available",
    in_carousel: false,
    view_count: 136,
    image_url: img(0),
    image_urls: [img(0), img(1), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-26",
    name: "Alfa Romeo Giulia",
    make: "Alfa Romeo",
    model: "Giulia",
    price: 44000,
    mileage: 16000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Automatic",
    description: "Alfa Romeo Giulia Ti Sport in Vesuvio Grey. Italian craftsmanship with rear-wheel drive dynamics.",
    features: ["Harman Kardon Audio", "Adaptive Damping", "Carbon Fiber Trim", "8.8\" Display", "Race Mode"],
    status: "available",
    in_carousel: false,
    view_count: 59,
    image_url: img(1),
    image_urls: [img(1), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-27",
    name: "Porsche 911 Carrera",
    make: "Porsche",
    model: "911 Carrera",
    price: 115000,
    mileage: 4000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L Twin-Turbo H6",
    transmission: "Automatic",
    description: "Porsche 911 Carrera S in GT Silver Metallic. Sport Chrono, PASM, and rear-axle steering.",
    features: ["Sport Chrono", "PASM", "Rear-Axle Steering", "Bose Surround", "Sport Exhaust"],
    status: "available",
    in_carousel: false,
    view_count: 197,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-28",
    name: "Honda Civic Type R",
    make: "Honda",
    model: "Civic Type R",
    price: 44500,
    mileage: 3000,
    year: 2023,
    fuel: "Petrol",
    type: "Hatchback",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 VTEC",
    transmission: "Manual",
    description: "Honda Civic Type R FL5 in Championship White. The ultimate front-wheel drive performance car.",
    features: ["Adaptive Dampers", "Brembo Brakes", "Limited Slip Diff", "Rev Match", "Honda LogR"],
    status: "available",
    in_carousel: false,
    view_count: 148,
    image_url: img(3),
    image_urls: [img(3), img(1), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-29",
    name: "BMW iX",
    make: "BMW",
    model: "iX",
    price: 84000,
    mileage: 10000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "BMW iX xDrive50 in Phytonic Blue. Shy-tech design with Harman Kardon Surround and iDrive 8.",
    features: ["iDrive 8", "Harman Kardon", "Panoramic Glass Roof", "Driving Assistant Pro", "5G Connectivity"],
    status: "available",
    in_carousel: false,
    view_count: 102,
    image_url: img(0),
    image_urls: [img(0), img(2), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-30",
    name: "Maserati Grecale",
    make: "Maserati",
    model: "Grecale",
    price: 66000,
    mileage: 11000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 + 48V",
    transmission: "Automatic",
    description: "Maserati Grecale Modena in Bianco Astro. Italian luxury SUV with Sonus Faber audio system.",
    features: ["Sonus Faber Audio", "Air Suspension", "12.3\" Cluster", "Corsa Mode", "Wireless Charging"],
    status: "available",
    in_carousel: false,
    view_count: 71,
    image_url: img(1),
    image_urls: [img(1), img(3), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
];
