import type { Vehicle, Lead, Transaction, Profile } from "@/lib/types";
import car1 from "@/assets/car-1.jpg";
import car2 from "@/assets/car-2.jpg";
import car3 from "@/assets/car-3.jpg";
import car4 from "@/assets/car-4.jpg";

const images = [car1, car2, car3, car4];
const img = (i: number): string => images[i % images.length];

const NOW = new Date().toISOString();

export const DEMO_CATEGORIES = [
  { id: "demo-cat-1", name: "Sedans",           slug: "sedans" },
  { id: "demo-cat-2", name: "SUVs",             slug: "suvs" },
  { id: "demo-cat-3", name: "Coupes & Sports",  slug: "coupes-sports" },
  { id: "demo-cat-4", name: "Hatchbacks",       slug: "hatchbacks" },
  { id: "demo-cat-5", name: "Electric & Hybrid",slug: "electric-hybrid" },
];

// Map vehicle type + fuel → demo category id
const catId = (type: string, fuel: string): string => {
  if (fuel === "Electric" || fuel === "Hybrid") return "demo-cat-5";
  if (type === "Sedan")    return "demo-cat-1";
  if (type === "SUV")      return "demo-cat-2";
  if (type === "Coupe")    return "demo-cat-3";
  if (type === "Hatchback")return "demo-cat-4";
  return "demo-cat-2";
};

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: "demo-1",
    name: "BMW 5 Series",
    make: "BMW",
    model: "5 Series",
    price: 42500,
    mileage: 28000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Automatic",
    description: "Impeccably maintained BMW 5 Series with full service history. Premium leather interior, adaptive cruise control, and panoramic sunroof.",
    features: ["Leather Interior", "Panoramic Roof", "Adaptive Cruise", "Parking Assist", "Heated Seats"],
    status: "available",
    in_carousel: true,
    view_count: 142,
    image_url: img(0),
    image_urls: [img(0), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-2",
    name: "Mercedes GLC",
    make: "Mercedes-Benz",
    model: "GLC",
    price: 55800,
    mileage: 15000,
    year: 2023,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo Diesel I4",
    transmission: "Automatic",
    description: "Near-new Mercedes GLC in stunning Cavansite Blue. AMG Line package with 20-inch alloys and Burmester sound system.",
    features: ["AMG Line", "Burmester Audio", "360° Camera", "Air Suspension", "Ambient Lighting"],
    status: "available",
    in_carousel: true,
    view_count: 178,
    image_url: img(1),
    image_urls: [img(1), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-3",
    name: "Audi S5 Sportback",
    make: "Audi",
    model: "S5 Sportback",
    price: 48900,
    mileage: 32000,
    year: 2021,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L TFSI V6",
    transmission: "Automatic",
    description: "Audi S5 Sportback with the legendary 3.0 TFSI engine. Quattro all-wheel drive, virtual cockpit, and Matrix LED headlights.",
    features: ["Quattro AWD", "Virtual Cockpit", "Matrix LED", "Bang & Olufsen", "Sport Differential"],
    status: "available",
    in_carousel: true,
    view_count: 95,
    image_url: img(2),
    image_urls: [img(2), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-4",
    name: "Porsche Cayenne",
    make: "Porsche",
    model: "Cayenne",
    price: 72000,
    mileage: 22000,
    year: 2022,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "3.0L V6 Hybrid",
    transmission: "Automatic",
    description: "Porsche Cayenne E-Hybrid in pristine white. Sport Chrono package, PASM air suspension, and 14-way adaptive sport seats.",
    features: ["Sport Chrono", "Air Suspension", "BOSE Audio", "Panoramic Roof", "Sport Exhaust"],
    status: "available",
    in_carousel: true,
    view_count: 163,
    image_url: img(3),
    image_urls: [img(3), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-5",
    name: "Toyota Camry",
    make: "Toyota",
    model: "Camry",
    price: 28500,
    mileage: 35000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.5L I4",
    transmission: "Automatic",
    description: "Reliable Toyota Camry with excellent fuel economy. Well-maintained with full dealer service history.",
    features: ["Apple CarPlay", "Lane Assist", "Blind Spot Monitor", "Dual Climate", "Keyless Entry"],
    status: "available",
    in_carousel: true,
    view_count: 87,
    image_url: img(0),
    image_urls: [img(0), img(1), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-6",
    name: "Range Rover Sport",
    make: "Land Rover",
    model: "Range Rover Sport",
    price: 68500,
    mileage: 18000,
    year: 2023,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "3.0L Turbo Diesel I6",
    transmission: "Automatic",
    description: "Range Rover Sport in Santorini Black. Dynamic pack, Meridian sound, and full off-road capability.",
    features: ["Meridian Audio", "Terrain Response", "Air Suspension", "Pixel LED", "Head-Up Display"],
    status: "available",
    in_carousel: true,
    view_count: 199,
    image_url: img(1),
    image_urls: [img(1), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-7",
    name: "Tesla Model 3",
    make: "Tesla",
    model: "Model 3",
    price: 38900,
    mileage: 20000,
    year: 2023,
    fuel: "Electric",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "Tesla Model 3 Long Range with Autopilot. Pearl White exterior with black premium interior.",
    features: ["Autopilot", "15\" Touchscreen", "Glass Roof", "Premium Audio", "Sentry Mode"],
    status: "available",
    in_carousel: false,
    view_count: 131,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-8",
    name: "Honda CR-V",
    make: "Honda",
    model: "CR-V",
    price: 32000,
    mileage: 25000,
    year: 2022,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "1.5L Turbo I4",
    transmission: "CVT",
    description: "Honda CR-V Touring with Honda Sensing suite. Spacious, reliable, and fuel-efficient.",
    features: ["Honda Sensing", "Wireless CarPlay", "Power Liftgate", "Heated Seats", "Moonroof"],
    status: "available",
    in_carousel: false,
    view_count: 54,
    image_url: img(3),
    image_urls: [img(3), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-9",
    name: "BMW M4 Competition",
    make: "BMW",
    model: "M4 Competition",
    price: 78000,
    mileage: 8000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L Twin-Turbo I6",
    transmission: "Automatic",
    description: "BMW M4 Competition in Isle of Man Green. Carbon fiber package, M Sport exhaust, and carbon ceramic brakes.",
    features: ["Carbon Ceramic Brakes", "M Sport Exhaust", "Harman Kardon", "Carbon Roof", "M Traction Control"],
    status: "available",
    in_carousel: false,
    view_count: 188,
    image_url: img(0),
    image_urls: [img(0), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-10",
    name: "Volkswagen Golf GTI",
    make: "Volkswagen",
    model: "Golf GTI",
    price: 34500,
    mileage: 12000,
    year: 2023,
    fuel: "Petrol",
    type: "Hatchback",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Manual",
    description: "VW Golf GTI Mk8 with Akrapovic exhaust. Dynamic Chassis Control and Vienna leather seats.",
    features: ["DCC Suspension", "Vienna Leather", "Digital Cockpit Pro", "Akrapovic Exhaust", "Keyless Go"],
    status: "available",
    in_carousel: false,
    view_count: 76,
    image_url: img(1),
    image_urls: [img(1), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-11",
    name: "Lexus RX 350",
    make: "Lexus",
    model: "RX 350",
    price: 52000,
    mileage: 19000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.4L Turbo I4",
    transmission: "Automatic",
    description: "Lexus RX 350 F Sport in Nori Green Pearl. Mark Levinson audio and heads-up display.",
    features: ["Mark Levinson Audio", "F Sport Package", "Panoramic View Monitor", "Adaptive Suspension", "14\" Touchscreen"],
    status: "available",
    in_carousel: false,
    view_count: 112,
    image_url: img(2),
    image_urls: [img(2), img(3), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-12",
    name: "Ford Mustang",
    make: "Ford",
    model: "Mustang",
    price: 45000,
    mileage: 15000,
    year: 2022,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "5.0L V8",
    transmission: "Manual",
    description: "Ford Mustang GT with Performance Pack Level 2. Magnetic dampers and Brembo brakes.",
    features: ["MagneRide Dampers", "Brembo Brakes", "Recaro Seats", "Active Exhaust", "Performance Pack"],
    status: "available",
    in_carousel: false,
    view_count: 155,
    image_url: img(3),
    image_urls: [img(3), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-13",
    name: "Hyundai Tucson",
    make: "Hyundai",
    model: "Tucson",
    price: 29500,
    mileage: 22000,
    year: 2023,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "1.6L Turbo Hybrid",
    transmission: "Automatic",
    description: "Hyundai Tucson Hybrid Limited with Bose audio. Parametric hidden LED daytime running lights.",
    features: ["Bose Audio", "Blind View Monitor", "Highway Driving Assist", "Rain Sensing Wipers", "Ambient Lighting"],
    status: "available",
    in_carousel: false,
    view_count: 43,
    image_url: img(0),
    image_urls: [img(0), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-14",
    name: "Audi Q7",
    make: "Audi",
    model: "Q7",
    price: 61000,
    mileage: 25000,
    year: 2022,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 7,
    engine: "3.0L TDI V6",
    transmission: "Automatic",
    description: "Audi Q7 S Line with 7 seats. Quattro AWD, virtual cockpit plus, and adaptive air suspension.",
    features: ["S Line", "7 Seats", "Virtual Cockpit Plus", "Adaptive Air Suspension", "Matrix LED"],
    status: "available",
    in_carousel: false,
    view_count: 97,
    image_url: img(1),
    image_urls: [img(1), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-15",
    name: "Mazda MX-5",
    make: "Mazda",
    model: "MX-5",
    price: 31000,
    mileage: 10000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "2.0L Skyactiv-G I4",
    transmission: "Manual",
    description: "Mazda MX-5 RF in Machine Grey. The ultimate lightweight sports car with retractable fastback.",
    features: ["Retractable Fastback", "Bose Audio", "Bilstein Dampers", "LSD", "Apple CarPlay"],
    status: "available",
    in_carousel: false,
    view_count: 68,
    image_url: img(2),
    image_urls: [img(2), img(1), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-16",
    name: "Mercedes E-Class",
    make: "Mercedes-Benz",
    model: "E-Class",
    price: 58000,
    mileage: 14000,
    year: 2023,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 + EQ Boost",
    transmission: "Automatic",
    description: "Mercedes E300 AMG Line with MBUX Superscreen. Augmented reality navigation and Burmester 4D audio.",
    features: ["MBUX Superscreen", "Burmester 4D", "AR Navigation", "Digital Light", "Air Body Control"],
    status: "available",
    in_carousel: false,
    view_count: 121,
    image_url: img(3),
    image_urls: [img(3), img(2), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-17",
    name: "Kia EV6",
    make: "Kia",
    model: "EV6",
    price: 46000,
    mileage: 8000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "Kia EV6 GT-Line with 800V ultra-fast charging. Vehicle-to-Load (V2L) capability and augmented reality HUD.",
    features: ["800V Charging", "V2L Capability", "AR Head-Up Display", "Meridian Audio", "Remote Smart Parking"],
    status: "available",
    in_carousel: false,
    view_count: 145,
    image_url: img(0),
    image_urls: [img(0), img(3), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-18",
    name: "Volvo XC60",
    make: "Volvo",
    model: "XC60",
    price: 49500,
    mileage: 20000,
    year: 2022,
    fuel: "Hybrid",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo + Electric",
    transmission: "Automatic",
    description: "Volvo XC60 Recharge T8 in Crystal White. Google built-in with Bowers & Wilkins premium audio.",
    features: ["Bowers & Wilkins Audio", "Google Built-In", "Pilot Assist", "Air Purifier", "360° Camera"],
    status: "available",
    in_carousel: false,
    view_count: 33,
    image_url: img(1),
    image_urls: [img(1), img(0), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-19",
    name: "Jaguar F-Pace",
    make: "Jaguar",
    model: "F-Pace",
    price: 54000,
    mileage: 18000,
    year: 2022,
    fuel: "Diesel",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo Diesel I4",
    transmission: "Automatic",
    description: "Jaguar F-Pace R-Dynamic S in Firenze Red. Pivi Pro infotainment and configurable ambient lighting.",
    features: ["Pivi Pro", "R-Dynamic Pack", "Configurable Ambient Lighting", "Activity Key", "ClearSight Mirror"],
    status: "available",
    in_carousel: false,
    view_count: 79,
    image_url: img(2),
    image_urls: [img(2), img(3), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-20",
    name: "Subaru WRX",
    make: "Subaru",
    model: "WRX",
    price: 35000,
    mileage: 16000,
    year: 2023,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.4L Turbo Boxer H4",
    transmission: "Manual",
    description: "Subaru WRX in WR Blue Pearl. Symmetrical AWD, 11.6\" tablet-style touchscreen, and EyeSight driver assist.",
    features: ["Symmetrical AWD", "11.6\" Touchscreen", "EyeSight", "Recaro Seats", "SI-Drive"],
    status: "available",
    in_carousel: false,
    view_count: 62,
    image_url: img(3),
    image_urls: [img(3), img(1), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-21",
    name: "Chevrolet Corvette",
    make: "Chevrolet",
    model: "Corvette",
    price: 82000,
    mileage: 5000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "6.2L V8",
    transmission: "Automatic",
    description: "C8 Corvette Stingray in Torch Red. Mid-engine layout, magnetic ride control, and performance data recorder.",
    features: ["Magnetic Ride Control", "Performance Data Recorder", "Front Lift", "Bose 14-Speaker", "GT2 Seats"],
    status: "available",
    in_carousel: false,
    view_count: 193,
    image_url: img(0),
    image_urls: [img(0), img(2), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-22",
    name: "Nissan Z",
    make: "Nissan",
    model: "Z",
    price: 42000,
    mileage: 9000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "3.0L Twin-Turbo V6",
    transmission: "Manual",
    description: "New Nissan Z Performance in Seiran Blue. Twin-turbo V6 with heritage-inspired design and modern technology.",
    features: ["Launch Control", "Sport Mode", "Bose Audio", "9\" Touchscreen", "Rev Match Control"],
    status: "available",
    in_carousel: false,
    view_count: 117,
    image_url: img(1),
    image_urls: [img(1), img(3), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-23",
    name: "Genesis GV70",
    make: "Genesis",
    model: "GV70",
    price: 47000,
    mileage: 14000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.5L Turbo I4",
    transmission: "Automatic",
    description: "Genesis GV70 Sport Prestige in Havana Red. Lexicon audio, fingerprint authentication, and 3D instrument cluster.",
    features: ["Lexicon Audio", "Fingerprint Auth", "3D Cluster", "Remote Smart Parking", "E-LSD"],
    status: "available",
    in_carousel: false,
    view_count: 88,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-24",
    name: "Toyota Supra",
    make: "Toyota",
    model: "GR Supra",
    price: 52500,
    mileage: 7000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 2,
    engine: "3.0L Turbo I6",
    transmission: "Automatic",
    description: "Toyota GR Supra 3.0 Premium in Renaissance Red. BMW-sourced inline-6 with active differential.",
    features: ["Active Differential", "Adaptive Suspension", "JBL Audio", "Head-Up Display", "Wireless CarPlay"],
    status: "available",
    in_carousel: false,
    view_count: 174,
    image_url: img(3),
    image_urls: [img(3), img(0), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-25",
    name: "Rivian R1S",
    make: "Rivian",
    model: "R1S",
    price: 79000,
    mileage: 6000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 7,
    engine: "Quad Motor Electric",
    transmission: "Single-Speed",
    description: "Rivian R1S Adventure Package in Compass Yellow. Quad motor with 835 hp and air suspension.",
    features: ["Quad Motor AWD", "Air Suspension", "Camp Speaker", "Gear Tunnel", "Reinforced Underbody"],
    status: "available",
    in_carousel: false,
    view_count: 136,
    image_url: img(0),
    image_urls: [img(0), img(1), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-26",
    name: "Alfa Romeo Giulia",
    make: "Alfa Romeo",
    model: "Giulia",
    price: 44000,
    mileage: 16000,
    year: 2022,
    fuel: "Petrol",
    type: "Sedan",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4",
    transmission: "Automatic",
    description: "Alfa Romeo Giulia Ti Sport in Vesuvio Grey. Italian craftsmanship with rear-wheel drive dynamics.",
    features: ["Harman Kardon Audio", "Adaptive Damping", "Carbon Fiber Trim", "8.8\" Display", "Race Mode"],
    status: "available",
    in_carousel: false,
    view_count: 59,
    image_url: img(1),
    image_urls: [img(1), img(2), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-27",
    name: "Porsche 911 Carrera",
    make: "Porsche",
    model: "911 Carrera",
    price: 115000,
    mileage: 4000,
    year: 2023,
    fuel: "Petrol",
    type: "Coupe",
    category_id: null,
    seats: 4,
    engine: "3.0L Twin-Turbo H6",
    transmission: "Automatic",
    description: "Porsche 911 Carrera S in GT Silver Metallic. Sport Chrono, PASM, and rear-axle steering.",
    features: ["Sport Chrono", "PASM", "Rear-Axle Steering", "Bose Surround", "Sport Exhaust"],
    status: "available",
    in_carousel: false,
    view_count: 197,
    image_url: img(2),
    image_urls: [img(2), img(0), img(3)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-28",
    name: "Honda Civic Type R",
    make: "Honda",
    model: "Civic Type R",
    price: 44500,
    mileage: 3000,
    year: 2023,
    fuel: "Petrol",
    type: "Hatchback",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 VTEC",
    transmission: "Manual",
    description: "Honda Civic Type R FL5 in Championship White. The ultimate front-wheel drive performance car.",
    features: ["Adaptive Dampers", "Brembo Brakes", "Limited Slip Diff", "Rev Match", "Honda LogR"],
    status: "available",
    in_carousel: false,
    view_count: 148,
    image_url: img(3),
    image_urls: [img(3), img(1), img(0)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-29",
    name: "BMW iX",
    make: "BMW",
    model: "iX",
    price: 84000,
    mileage: 10000,
    year: 2023,
    fuel: "Electric",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    description: "BMW iX xDrive50 in Phytonic Blue. Shy-tech design with Harman Kardon Surround and iDrive 8.",
    features: ["iDrive 8", "Harman Kardon", "Panoramic Glass Roof", "Driving Assistant Pro", "5G Connectivity"],
    status: "available",
    in_carousel: false,
    view_count: 102,
    image_url: img(0),
    image_urls: [img(0), img(2), img(1)],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "demo-30",
    name: "Maserati Grecale",
    make: "Maserati",
    model: "Grecale",
    price: 66000,
    mileage: 11000,
    year: 2023,
    fuel: "Petrol",
    type: "SUV",
    category_id: null,
    seats: 5,
    engine: "2.0L Turbo I4 + 48V",
    transmission: "Automatic",
    description: "Maserati Grecale Modena in Bianco Astro. Italian luxury SUV with Sonus Faber audio system.",
    features: ["Sonus Faber Audio", "Air Suspension", "12.3\" Cluster", "Corsa Mode", "Wireless Charging"],
    status: "available",
    in_carousel: false,
    view_count: 71,
    image_url: img(1),
    image_urls: [img(1), img(3), img(2)],
    created_at: NOW,
    updated_at: NOW,
  },
].map((v) => ({ ...v, category_id: catId(v.type, v.fuel) })) as Vehicle[];

// ─── Demo Leads ──────────────────────────────────────────────────────────────

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

export const DEMO_LEADS: Lead[] = [
  { id: "dl-1", user_id: null, name: "James Harrington", email: "james.h@example.com", phone: "515-203-4812", vehicle_id: "demo-2", vehicle_name: "Mercedes GLC 300", message: "Is this still available? I'd love to schedule a test drive this weekend.", lead_type: "test_drive", status: "new", created_at: daysAgo(0) },
  { id: "dl-2", user_id: null, name: "Priya Nair", email: "priya.n@example.com", phone: "515-889-2201", vehicle_id: "demo-1", vehicle_name: "BMW 5 Series", message: "Interested in the BMW. Can you share the full service history?", lead_type: "inquiry", status: "contacted", created_at: daysAgo(1) },
  { id: "dl-3", user_id: null, name: "Carlos Mendoza", email: "cmendoza@example.com", phone: null, vehicle_id: "demo-5", vehicle_name: "Tesla Model 3", message: "What's the range and warranty remaining on the battery?", lead_type: "inquiry", status: "new", created_at: daysAgo(1) },
  { id: "dl-4", user_id: null, name: "Sophie Andersson", email: "sophie.a@example.com", phone: "515-442-7790", vehicle_id: "demo-3", vehicle_name: "Audi Q5", message: "Looking for an SUV for family trips. Is the Q5 still under manufacturer warranty?", lead_type: "inquiry", status: "new", created_at: daysAgo(2) },
  { id: "dl-5", user_id: null, name: "Marcus Webb", email: "marcuswebb@example.com", phone: "515-610-5544", vehicle_id: "demo-21", vehicle_name: "Chevrolet Corvette", message: "I'm very interested in the Corvette. What's your best out-the-door price?", lead_type: "inquiry", status: "contacted", created_at: daysAgo(3) },
  { id: "dl-6", user_id: null, name: "Lin Zhao", email: "lin.zhao@example.com", phone: null, vehicle_id: null, vehicle_name: null, message: "Do you have any luxury sedans under $50K coming in soon?", lead_type: "contact", status: "new", created_at: daysAgo(4) },
  { id: "dl-7", user_id: null, name: "Emily Carter", email: "emilycarter@example.com", phone: "515-777-3380", vehicle_id: "demo-4", vehicle_name: "Porsche Cayenne", message: "Can I bring the car to my mechanic for a pre-purchase inspection?", lead_type: "inquiry", status: "closed", created_at: daysAgo(5) },
  { id: "dl-8", user_id: null, name: "Derek Thompson", email: "derek.t@example.com", phone: "515-234-9921", vehicle_id: "demo-12", vehicle_name: "Ford Mustang", message: "Would you consider a trade-in on my 2019 Camaro SS?", lead_type: "test_drive", status: "new", created_at: daysAgo(5) },
  { id: "dl-9", user_id: null, name: "Aisha Kamara", email: "akamara@example.com", phone: null, vehicle_id: "demo-13", vehicle_name: "Hyundai Tucson", message: "Is financing available? Looking for 60-month terms.", lead_type: "inquiry", status: "contacted", created_at: daysAgo(7) },
  { id: "dl-10", user_id: null, name: "Ryan O'Brien", email: "ryanobrienx@example.com", phone: "515-501-6677", vehicle_id: "demo-6", vehicle_name: "Honda Accord", message: "I live in Des Moines — can I come in tomorrow for a test drive?", lead_type: "test_drive", status: "closed", created_at: daysAgo(9) },
  { id: "dl-11", user_id: null, name: "Natalie Brooke", email: "natalie.b@example.com", phone: "515-388-2209", vehicle_id: "demo-27", vehicle_name: "Porsche 911 Carrera", message: "Is there a CPO warranty on the 911? Looking for extended coverage.", lead_type: "inquiry", status: "new", created_at: daysAgo(11) },
  { id: "dl-12", user_id: null, name: "Hassan Al-Farsi", email: "hassan.af@example.com", phone: null, vehicle_id: "demo-8", vehicle_name: "Toyota Camry", message: "I'd like to schedule a viewing for Saturday morning.", lead_type: "test_drive", status: "new", created_at: daysAgo(13) },
];

// ─── Demo Transactions ───────────────────────────────────────────────────────
export const DEMO_TRANSACTIONS: Transaction[] = [
  { id: "dt-1", idempotency_key: "ik-dt-1", vehicle_id: "demo-7", vehicle_name: "Range Rover Sport", buyer_id: null, buyer_name: "Emily Carter", buyer_email: "emilycarter@example.com", amount: 68500, status: "completed", created_at: daysAgo(6) },
  { id: "dt-2", idempotency_key: "ik-dt-2", vehicle_id: "demo-9", vehicle_name: "Kia EV6", buyer_id: null, buyer_name: "Ryan O'Brien", buyer_email: "ryanobrienx@example.com", amount: 41200, status: "completed", created_at: daysAgo(11) },
  { id: "dt-3", idempotency_key: "ik-dt-3", vehicle_id: "demo-6", vehicle_name: "Honda Accord", buyer_id: null, buyer_name: "Priya Nair", buyer_email: "priya.n@example.com", amount: 29800, status: "completed", created_at: daysAgo(15) },
  { id: "dt-4", idempotency_key: "ik-dt-4", vehicle_id: "demo-18", vehicle_name: "Subaru Outback", buyer_id: null, buyer_name: "Sophie Andersson", buyer_email: "sophie.a@example.com", amount: 35500, status: "completed", created_at: daysAgo(22) },
  { id: "dt-5", idempotency_key: "ik-dt-5", vehicle_id: "demo-14", vehicle_name: "Audi Q7", buyer_id: null, buyer_name: "Lin Zhao", buyer_email: "lin.zhao@example.com", amount: 61000, status: "pending", created_at: daysAgo(2) },
  { id: "dt-6", idempotency_key: "ik-dt-6", vehicle_id: "demo-16", vehicle_name: "Mazda CX-5", buyer_id: null, buyer_name: "Marcus Webb", buyer_email: "marcuswebb@example.com", amount: 31000, status: "completed", created_at: daysAgo(30) },
  { id: "dt-7", idempotency_key: "ik-dt-7", vehicle_id: "demo-24", vehicle_name: "Genesis GV80", buyer_id: null, buyer_name: "Natalie Brooke", buyer_email: "natalie.b@example.com", amount: 58000, status: "pending", created_at: daysAgo(1) },
];

// ─── Demo Users ──────────────────────────────────────────────────────────────
export const DEMO_USERS: (Profile & { email?: string; favorites_count?: number; leads_count?: number })[] = [
  { id: "du-1", name: "Admin Account", email: "iowaautotrust@gmail.com", phone: null, location: "Iowa City, IA", is_admin: true, is_manager: false, created_at: daysAgo(90), favorites_count: 0, leads_count: 0 },
  { id: "du-2", name: "James Harrington", email: "james.h@example.com", phone: "515-203-4812", location: "Des Moines, IA", is_admin: false, is_manager: false, created_at: daysAgo(14), favorites_count: 3, leads_count: 1 },
  { id: "du-3", name: "Priya Nair", email: "priya.n@example.com", phone: "515-889-2201", location: "Cedar Rapids, IA", is_admin: false, is_manager: false, created_at: daysAgo(20), favorites_count: 5, leads_count: 2 },
  { id: "du-4", name: "Carlos Mendoza", email: "cmendoza@example.com", phone: null, location: null, is_admin: false, is_manager: false, created_at: daysAgo(8), favorites_count: 1, leads_count: 1 },
  { id: "du-5", name: "Sarah Mitchell", email: "sarah.m@example.com", phone: "515-773-4490", location: "Ames, IA", is_admin: false, is_manager: true, created_at: daysAgo(45), favorites_count: 0, leads_count: 0 },
  { id: "du-6", name: "Marcus Webb", email: "marcuswebb@example.com", phone: "515-610-5544", location: "Davenport, IA", is_admin: false, is_manager: false, created_at: daysAgo(31), favorites_count: 2, leads_count: 1 },
  { id: "du-7", name: "Emily Carter", email: "emilycarter@example.com", phone: "515-777-3380", location: "Sioux City, IA", is_admin: false, is_manager: false, created_at: daysAgo(40), favorites_count: 4, leads_count: 1 },
  { id: "du-8", name: "Ryan O'Brien", email: "ryanobrienx@example.com", phone: "515-501-6677", location: "Iowa City, IA", is_admin: false, is_manager: false, created_at: daysAgo(60), favorites_count: 1, leads_count: 1 },
];
